POST http://localhost:3000/api/usuario
Content-Type: application/json

{
    "id_usuario":"idDoUsuario",
    "nome":"Rafael",
    "email":"email@email.com",
    "data_nasc":"2012-04-23T18:25:43.511Z",
    "senha":"123456",
    "telefone":"435345345",
    "cpf":"345345345"
}

###

GET http://localhost:3000/